import type { NextPage } from "next";
import Head from "next/head";
import ListOwners from "../containers/ListOwner";
import VisitorInfo from "../containers/VisitorInfo";
import ListNewTokens from "../containers/ListNewTokens";
import styles from "../styles/Home.module.css";
import { Grid } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>get top 5 holders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}> the visitors info</h3>
        <br></br>
        <Grid container spacing={2}>
          <Grid item xs={4}>
            <h3 className={styles.title}>General Information</h3>
            <VisitorInfo />
          </Grid>
          <Grid item xs={4}>
            <h2 className={styles.title}>Get Top 5 Holders of Visitors</h2>
            <ListOwners />
          </Grid>
          <Grid item xs={4}>
            <h2 className={styles.title}>Get Last 5 Mint</h2>
            <ListNewTokens />
          </Grid>
        </Grid>

        <footer className={styles.footer}></footer>
      </main>
    </div>
  );
};

export default Home;
