import type { NextPage } from "next";
import Head from "next/head";
import ListOwners from "../containers/ListOwner";
import styles from "../styles/Home.module.css";
import { ApolloClient, InMemoryCache, ApolloProvider, useQuery, gql } from "@apollo/client";

const client = new ApolloClient({
  uri: process.env.NEXT_PUBLIC_API_GRAPH_VISITORS,
  cache: new InMemoryCache(),
});

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>get top 5 holders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ApolloProvider client={client}>
        <main className={styles.main}>
          <h1 className={styles.title}>Get Top 5 Holders of Visitors</h1>

          <div className={styles.grid}>
            <ListOwners />
          </div>
          <footer className={styles.footer}>testing</footer>
        </main>
      </ApolloProvider>
    </div>
  );
};

export default Home;
